---
title: "R Notebook"
output: html_notebook
---

-- -----------------------------
<!-- 1. CONOCIENDO LOS DATOS -->
-- -----------------------------
```{r}
#1.1
library(tidyverse)
#1.2
yearly <- read_csv("deaths_handwashing.csv")
#1.3
yearly
```
-- ---------------------------------------
<!-- 2. EL ALARMANTE NUMERO DE MUERTES -->
-- ---------------------------------------
```{r}
#2.1
yearly <- yearly %>%
  mutate(proportion_deaths = (deaths/births)*100)
#2.2
yearly

```
-- --------------------------------
<!-- 3. MUERTES EN LAS CLINICAS -->
-- --------------------------------
```{r}
#3.1 y 3.2
ggplot(yearly, aes(x=year, y=proportion_deaths, color=clinic)) +
  geom_line()

```
-- ----------------------------------------
<!-- 4. COMIENZA EL LAVADO DE LAS MANOS -->
-- ----------------------------------------
```{r}
#4.1
monthly <- read_csv("deaths_clinic_1.csv")

#4.2
monthly <- monthly %>%
    mutate(proportion_deaths = (deaths/births)*100)

#4.3
head(monthly, 5)

```
-- ------------------------------------------
<!-- 5. EL EFECTO DEL LAVADO DE LAS MANOS -->
-- ------------------------------------------
```{r}
#5.1 y 5.2
ggplot(monthly, aes(x=date, y=proportion_deaths)) +
  geom_line(colour = 'blue') +
  labs(x="Fecha", y="Proporción (Fallecido/Nacidos)", title="Grafica de Proporcion de Fallecidos por Fecha", subtitle="Clinica #1")

```
-- -------------------------------------------
<!-- 6. LOS RESULTADOS DEL LAVADO DE MANOS -->
-- -------------------------------------------
```{r}
#6.1
monthly <- monthly %>%
  #mutate (handwashing_started = ifelse (as.numeric(format(date,'%Y')) >= 1847, TRUE, FALSE))
  mutate (handwashing_started = ifelse (date >= '1847/01/01', TRUE, FALSE))
  
#6.2 y 6.3
ggplot(monthly, aes(x=date, y=proportion_deaths, color = handwashing_started)) +
  geom_line() +
  #para ver mas definidos los puntos de interseccion x,y
  geom_point() +
  labs(x="Fecha", y="Proporción (Fallecido/Nacidos)", title="Grafica de Proporcion de Fallecidos por Fecha", subtitle="Clinica #1")

```
-- ---------------------------------------------
<!-- 7. ¿MAS LAVADO DE MANOS, MENOS MUERTES? -->
-- ---------------------------------------------
```{r}
#7.1 y 7.2
month_summary <- monthly %>%
  group_by(handwashing_started) %>%
  summarise(mean_propotion_deaths = mean(proportion_deaths))
#7.3
month_summary

```
